// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package about

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "cspage/pkg/mon/web/templates"

func aboutTempl() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<article class=\"well w-full md:w-fit max-w-6xl\"><header><a href=\"/about\" class=\"link\">About</a></header><p class=\"mt-4 text-gray-500 dark:text-gray-400\">WARNING: This is an experimental project. The data is real, but the interpretation is not to be relied upon.</p><hr class=\"my-4 lg:my-8 border-gray-200 dark:border-gray-700\"><section class=\"md:grid md:grid-cols-5 gap-4 lg:gap-8\"><div class=\"col-span-2\"><h2 class=\"text-base sm:text-lg md:text-xl font-bold\">Why</h2><p class=\"py-2 lg:py-4\">The goal of this project is simple: to bring greater transparency to the operational status of major public cloud services (and potentially other SaaS platforms). In today&rsquo;s software-driven world, so much depends on the reliability of big cloud providers. While each of them offers a status page, it often paints a picture that looks perfect &mdash; perhaps a little too perfect.</p></div><div class=\"py-2 col-span-3\"><div class=\"overflow-hidden\"><img alt=\"Motivation\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(templates.StaticURL + "img/hn.webp")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `mon/web/views/about/about.templ`, Line: 30, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"max-h-48 rounded-md\"></div></div></section><hr class=\"my-4 lg:my-8 border-gray-200 dark:border-gray-700\"><section class=\"md:grid md:grid-cols-5 gap-4 lg:gap-8\"><div class=\"col-span-3\"><h2 class=\"text-base sm:text-lg md:text-xl font-bold\">How it works</h2><div class=\"py-2 lg:py-4\"><p class=\"md:text-base\">The monitoring system is straightforward:</p><ol class=\"list-decimal list-inside pl-2 mt-1\"><li><b>Monitoring Agents:</b> A simple monitoring agent is deployed in every region of each cloud (AWS, Azure, GCP).</li><li><b>Periodic Probes:</b> These agents regularly run &quot;monitoring probes&quot; - small tests that interact with various managed services in each cloud region.</li><li><b>Official SDKs:</b> Monitoring probes are simply calling cloud's APIs using their official SDKs.</li><li><b>Regional Testing:</b> All tests are performed within the same region as the monitoring agent so that reported latencies are purely regional.</li><li><b>Data Collection:</b> Results from these probes are asynchronously collected in a central database and displayed on this site.</li><li><b>Continuous Analysis:</b> Collected data are constantly analyzed for potential latency issues and probe failures. If something seems off, the system generates alerts, which could escalate into incidents (once verified).</li></ol><p class=\"mt-1 lg:mt-3 md:text-base\">Alert and incident severities:</p><ul class=\"list-disc list-inside pl-2 mt-1\"><li><b>🟨&nbsp;Yellow:</b> automated alerts triggered by increased latencies (can be caused by a problem within the monitoring system).</li><li><b>🟧&nbsp;Orange:</b> automated alerts triggered by probe failures (can be caused by a problem within the monitoring system).</li><li><b>🟥&nbsp;Red:</b> confirmed incident (something is wrong in the cloud).</li></ul></div></div><div class=\"py-2 col-span-2\"><div class=\"overflow-hidden\"><img alt=\"architecture\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templates.StaticURL + "img/architecture.webp")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `mon/web/views/about/about.templ`, Line: 60, Col: 80}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"max-h-[360px] rounded-md\"></div></div></section><hr class=\"my-4 lg:my-8 border-gray-200 dark:border-gray-700\"><section class=\"sm:grid sm:grid-cols-5 gap-4 lg:gap-8\"><div class=\"col-span-2\"><h2 class=\"text-base sm:text-lg md:text-xl font-bold\">Ideas</h2><p class=\"py-2 lg:py-4\">While it's not impossible to monitor everything all the time, this project wants to grow and is open to suggestions! If you feel that something needs to be monitored or have other ideas please let me know at <i>daniel (at) kontsek.sk</i>.</p></div><div class=\"py-2 col-span-3\"><div class=\"overflow-hidden\"><img alt=\"Ideas\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templates.StaticURL + "img/dalle.webp")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `mon/web/views/about/about.templ`, Line: 77, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"max-h-64 rounded-lg\"></div></div></section></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
