apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion | quote }}
data:
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  {{- range $key,$value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
