apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  {{- range $key,$value := .Values.secret_env }}
  {{ $key }}: {{ $value | b64enc -}}
  {{ end }}
