---
apiVersion: v1
kind: Secret
metadata:
  name: role-${NAME}
  namespace: postgres
type: kubernetes.io/basic-auth
data:
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: ${NAME}-postgres
  namespace: default
type: Opaque
data:
  DATABASE_WRITE_URL: "${DB_WRITE_URL}"
  DATABASE_READ_URL:  "${DB_READ_URL}"

