// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: pkg/pb/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentAction int32

const (
	AgentAction_AGENT_UNKNOWN     AgentAction = 0
	AgentAction_AGENT_START       AgentAction = 1
	AgentAction_AGENT_STOP_MANUAL AgentAction = 2
	AgentAction_AGENT_STOPPING    AgentAction = 4
	AgentAction_AGENT_STOP        AgentAction = 6
)

// Enum value maps for AgentAction.
var (
	AgentAction_name = map[int32]string{
		0: "AGENT_UNKNOWN",
		1: "AGENT_START",
		2: "AGENT_STOP_MANUAL",
		4: "AGENT_STOPPING",
		6: "AGENT_STOP",
	}
	AgentAction_value = map[string]int32{
		"AGENT_UNKNOWN":     0,
		"AGENT_START":       1,
		"AGENT_STOP_MANUAL": 2,
		"AGENT_STOPPING":    4,
		"AGENT_STOP":        6,
	}
)

func (x AgentAction) Enum() *AgentAction {
	p := new(AgentAction)
	*p = x
	return p
}

func (x AgentAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_agent_proto_enumTypes[0].Descriptor()
}

func (AgentAction) Type() protoreflect.EnumType {
	return &file_pkg_pb_agent_proto_enumTypes[0]
}

func (x AgentAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentAction.Descriptor instead.
func (AgentAction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_agent_proto_rawDescGZIP(), []int{0}
}

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action      AgentAction            `protobuf:"varint,2,opt,name=action,proto3,enum=AgentAction" json:"action,omitempty"`
	Time        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Version     string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Hostname    string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress   string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CloudRegion string                 `protobuf:"bytes,6,opt,name=cloud_region,json=cloudRegion,proto3" json:"cloud_region,omitempty"`
	CloudZone   string                 `protobuf:"bytes,7,opt,name=cloud_zone,json=cloudZone,proto3" json:"cloud_zone,omitempty"`
	Sysinfo     []byte                 `protobuf:"bytes,15,opt,name=sysinfo,proto3" json:"sysinfo,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_pkg_pb_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetAction() AgentAction {
	if x != nil {
		return x.Action
	}
	return AgentAction_AGENT_UNKNOWN
}

func (x *Agent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Agent) GetCloudRegion() string {
	if x != nil {
		return x.CloudRegion
	}
	return ""
}

func (x *Agent) GetCloudZone() string {
	if x != nil {
		return x.CloudZone
	}
	return ""
}

func (x *Agent) GetSysinfo() []byte {
	if x != nil {
		return x.Sysinfo
	}
	return nil
}

var File_pkg_pb_agent_proto protoreflect.FileDescriptor

var file_pkg_pb_agent_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x24, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x79, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73,
	0x79, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x2a, 0x6c, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x47, 0x45, 0x4e,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x47, 0x45,
	0x4e, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4d, 0x41, 0x4e, 0x55, 0x41, 0x4c, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49,
	0x4e, 0x47, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54,
	0x4f, 0x50, 0x10, 0x06, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x73, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_agent_proto_rawDescOnce sync.Once
	file_pkg_pb_agent_proto_rawDescData = file_pkg_pb_agent_proto_rawDesc
)

func file_pkg_pb_agent_proto_rawDescGZIP() []byte {
	file_pkg_pb_agent_proto_rawDescOnce.Do(func() {
		file_pkg_pb_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_agent_proto_rawDescData)
	})
	return file_pkg_pb_agent_proto_rawDescData
}

var file_pkg_pb_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pb_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_pb_agent_proto_goTypes = []any{
	(AgentAction)(0),              // 0: AgentAction
	(*Agent)(nil),                 // 1: Agent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_pb_agent_proto_depIdxs = []int32{
	0, // 0: Agent.action:type_name -> AgentAction
	2, // 1: Agent.time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_agent_proto_init() }
func file_pkg_pb_agent_proto_init() {
	if File_pkg_pb_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_agent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_agent_proto_goTypes,
		DependencyIndexes: file_pkg_pb_agent_proto_depIdxs,
		EnumInfos:         file_pkg_pb_agent_proto_enumTypes,
		MessageInfos:      file_pkg_pb_agent_proto_msgTypes,
	}.Build()
	File_pkg_pb_agent_proto = out.File
	file_pkg_pb_agent_proto_rawDesc = nil
	file_pkg_pb_agent_proto_goTypes = nil
	file_pkg_pb_agent_proto_depIdxs = nil
}
