// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: pkg/pb/incident.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncidentStatus int32

const (
	IncidentStatus_INCIDENT_ANY    IncidentStatus = 0
	IncidentStatus_INCIDENT_CLOSED IncidentStatus = 1
	IncidentStatus_INCIDENT_OPEN   IncidentStatus = 3
)

// Enum value maps for IncidentStatus.
var (
	IncidentStatus_name = map[int32]string{
		0: "INCIDENT_ANY",
		1: "INCIDENT_CLOSED",
		3: "INCIDENT_OPEN",
	}
	IncidentStatus_value = map[string]int32{
		"INCIDENT_ANY":    0,
		"INCIDENT_CLOSED": 1,
		"INCIDENT_OPEN":   3,
	}
)

func (x IncidentStatus) Enum() *IncidentStatus {
	p := new(IncidentStatus)
	*p = x
	return p
}

func (x IncidentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_incident_proto_enumTypes[0].Descriptor()
}

func (IncidentStatus) Type() protoreflect.EnumType {
	return &file_pkg_pb_incident_proto_enumTypes[0]
}

func (x IncidentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentStatus.Descriptor instead.
func (IncidentStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_incident_proto_rawDescGZIP(), []int{0}
}

type IncidentSeverity int32

const (
	IncidentSeverity_INCIDENT_NONE   IncidentSeverity = 0 // gray or green
	IncidentSeverity_INCIDENT_LOW    IncidentSeverity = 1 // yellow
	IncidentSeverity_INCIDENT_MEDIUM IncidentSeverity = 2 // orange
	IncidentSeverity_INCIDENT_HIGH   IncidentSeverity = 3 // red
)

// Enum value maps for IncidentSeverity.
var (
	IncidentSeverity_name = map[int32]string{
		0: "INCIDENT_NONE",
		1: "INCIDENT_LOW",
		2: "INCIDENT_MEDIUM",
		3: "INCIDENT_HIGH",
	}
	IncidentSeverity_value = map[string]int32{
		"INCIDENT_NONE":   0,
		"INCIDENT_LOW":    1,
		"INCIDENT_MEDIUM": 2,
		"INCIDENT_HIGH":   3,
	}
)

func (x IncidentSeverity) Enum() *IncidentSeverity {
	p := new(IncidentSeverity)
	*p = x
	return p
}

func (x IncidentSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_incident_proto_enumTypes[1].Descriptor()
}

func (IncidentSeverity) Type() protoreflect.EnumType {
	return &file_pkg_pb_incident_proto_enumTypes[1]
}

func (x IncidentSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentSeverity.Descriptor instead.
func (IncidentSeverity) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_incident_proto_rawDescGZIP(), []int{1}
}

type CloudRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *CloudRegion) Reset() {
	*x = CloudRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_incident_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudRegion) ProtoMessage() {}

func (x *CloudRegion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_incident_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudRegion.ProtoReflect.Descriptor instead.
func (*CloudRegion) Descriptor() ([]byte, []int) {
	return file_pkg_pb_incident_proto_rawDescGZIP(), []int{0}
}

func (x *CloudRegion) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type Incident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated,proto3" json:"updated,omitempty"`
	TimeBegin    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_begin,json=timeBegin,proto3" json:"time_begin,omitempty"`
	TimeEnd      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Severity     IncidentSeverity       `protobuf:"varint,8,opt,name=severity,proto3,enum=IncidentSeverity" json:"severity,omitempty"`
	Status       IncidentStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=IncidentStatus" json:"status,omitempty"`
	CloudRegions []*CloudRegion         `protobuf:"bytes,10,rep,name=cloud_regions,json=cloudRegions,proto3" json:"cloud_regions,omitempty"`
	Alerts       []*Alert               `protobuf:"bytes,11,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Data         []byte                 `protobuf:"bytes,15,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Incident) Reset() {
	*x = Incident{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_incident_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_incident_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_pkg_pb_incident_proto_rawDescGZIP(), []int{1}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Incident) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *Incident) GetTimeBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeBegin
	}
	return nil
}

func (x *Incident) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *Incident) GetSeverity() IncidentSeverity {
	if x != nil {
		return x.Severity
	}
	return IncidentSeverity_INCIDENT_NONE
}

func (x *Incident) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_ANY
}

func (x *Incident) GetCloudRegions() []*CloudRegion {
	if x != nil {
		return x.CloudRegions
	}
	return nil
}

func (x *Incident) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *Incident) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_pb_incident_proto protoreflect.FileDescriptor

var file_pkg_pb_incident_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0b,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x22, 0xb7, 0x03, 0x0a, 0x08, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x65, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x2d,
	0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31, 0x0a, 0x0d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x06, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x6c, 0x65, 0x72,
	0x74, 0x52, 0x06, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x4a, 0x0a,
	0x0e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x4e, 0x59, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45,
	0x4e, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x03, 0x2a, 0x5f, 0x0a, 0x10, 0x49, 0x6e, 0x63,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x11, 0x0a,
	0x0d, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x57,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x4d,
	0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x43, 0x49, 0x44,
	0x45, 0x4e, 0x54, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10, 0x03, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x73,
	0x70, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_incident_proto_rawDescOnce sync.Once
	file_pkg_pb_incident_proto_rawDescData = file_pkg_pb_incident_proto_rawDesc
)

func file_pkg_pb_incident_proto_rawDescGZIP() []byte {
	file_pkg_pb_incident_proto_rawDescOnce.Do(func() {
		file_pkg_pb_incident_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_incident_proto_rawDescData)
	})
	return file_pkg_pb_incident_proto_rawDescData
}

var file_pkg_pb_incident_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_pb_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_incident_proto_goTypes = []any{
	(IncidentStatus)(0),           // 0: IncidentStatus
	(IncidentSeverity)(0),         // 1: IncidentSeverity
	(*CloudRegion)(nil),           // 2: CloudRegion
	(*Incident)(nil),              // 3: Incident
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Alert)(nil),                 // 5: Alert
}
var file_pkg_pb_incident_proto_depIdxs = []int32{
	4, // 0: Incident.created:type_name -> google.protobuf.Timestamp
	4, // 1: Incident.updated:type_name -> google.protobuf.Timestamp
	4, // 2: Incident.time_begin:type_name -> google.protobuf.Timestamp
	4, // 3: Incident.time_end:type_name -> google.protobuf.Timestamp
	1, // 4: Incident.severity:type_name -> IncidentSeverity
	0, // 5: Incident.status:type_name -> IncidentStatus
	2, // 6: Incident.cloud_regions:type_name -> CloudRegion
	5, // 7: Incident.alerts:type_name -> Alert
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_pb_incident_proto_init() }
func file_pkg_pb_incident_proto_init() {
	if File_pkg_pb_incident_proto != nil {
		return
	}
	file_pkg_pb_alert_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_incident_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CloudRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_incident_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Incident); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_incident_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_incident_proto_goTypes,
		DependencyIndexes: file_pkg_pb_incident_proto_depIdxs,
		EnumInfos:         file_pkg_pb_incident_proto_enumTypes,
		MessageInfos:      file_pkg_pb_incident_proto_msgTypes,
	}.Build()
	File_pkg_pb_incident_proto = out.File
	file_pkg_pb_incident_proto_rawDesc = nil
	file_pkg_pb_incident_proto_goTypes = nil
	file_pkg_pb_incident_proto_depIdxs = nil
}
