// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: pkg/pb/ping.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job     *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Sysstat *SysStat `protobuf:"bytes,10,opt,name=sysstat,proto3" json:"sysstat,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_ping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_ping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_pb_ping_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Ping) GetSysstat() *SysStat {
	if x != nil {
		return x.Sysstat
	}
	return nil
}

var File_pkg_pb_ping_proto protoreflect.FileDescriptor

var file_pkg_pb_ping_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x79,
	0x73, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x04, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x04, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x22, 0x0a, 0x07, 0x73,
	0x79, 0x73, 0x73, 0x74, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53,
	0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x07, 0x73, 0x79, 0x73, 0x73, 0x74, 0x61, 0x74, 0x42,
	0x0f, 0x5a, 0x0d, 0x63, 0x73, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_ping_proto_rawDescOnce sync.Once
	file_pkg_pb_ping_proto_rawDescData = file_pkg_pb_ping_proto_rawDesc
)

func file_pkg_pb_ping_proto_rawDescGZIP() []byte {
	file_pkg_pb_ping_proto_rawDescOnce.Do(func() {
		file_pkg_pb_ping_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_ping_proto_rawDescData)
	})
	return file_pkg_pb_ping_proto_rawDescData
}

var file_pkg_pb_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_pb_ping_proto_goTypes = []any{
	(*Ping)(nil),    // 0: Ping
	(*Job)(nil),     // 1: Job
	(*SysStat)(nil), // 2: SysStat
}
var file_pkg_pb_ping_proto_depIdxs = []int32{
	1, // 0: Ping.job:type_name -> Job
	2, // 1: Ping.sysstat:type_name -> SysStat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_ping_proto_init() }
func file_pkg_pb_ping_proto_init() {
	if File_pkg_pb_ping_proto != nil {
		return
	}
	file_pkg_pb_job_proto_init()
	file_pkg_pb_sysinfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_ping_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_ping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_ping_proto_goTypes,
		DependencyIndexes: file_pkg_pb_ping_proto_depIdxs,
		MessageInfos:      file_pkg_pb_ping_proto_msgTypes,
	}.Build()
	File_pkg_pb_ping_proto = out.File
	file_pkg_pb_ping_proto_rawDesc = nil
	file_pkg_pb_ping_proto_goTypes = nil
	file_pkg_pb_ping_proto_depIdxs = nil
}
